# -*- coding: utf-8 -*-
"""CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12frRkycluZA1sENg6GwCZtAZaQ6WcJu1
"""

import requests

def lala():
  print('CEPython')
  cep = input('Digite o CEP para a consulta: ')

  while len(cep) != 8:
    print('Quantidade de dígitos invádia!!!')
    cep = input('Digite o CEP para a consulta: ')
 
 
  caixinha = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco = caixinha.json()
 
  if 'erro' not in endereco:
    print('==> CEP ENCONTRADO <==')

    #abaixo 3 formas de fazer a mesma coisa
    print("CEP: " + endereco['cep'])
    print('Cidade: {}'.format(endereco['localidade']))
    print(f'Estado: {endereco["uf"]}')
    #/ a mais usada é essa última de cima

    print('Rua: {}'.format(endereco['logradouro']))
    print('DDD: {}'.format(endereco['ddd']))
    print('---------------------------------')
  else:
    print('{}: CEP Inválido!'.format(cep))
    print('---------------------------------')

  def validacao():
    opcao = input('Deseja realizar outra consulta: \n 1. Sim \n 2. Sair \n')
    if opcao == "1" or opcao == "2":
      if int(opcao) == 1:
        lala()
      else:
        print('Até mais!!!!')
    else:
      print('Amigão, digite 1 ou 2 apenas!!!')
      validacao()
  validacao()
lala()

